### ISSUE TITLE
npm install?

### ISSUE THREAD

**Issue by eviewei** [smka/homebridge-broadlink-platform#1]
sudo npm install -g homebridge-broadlink-mp
npm ERR! code E404
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/homebridge-broadlink-mp
npm ERR! 404 
npm ERR! 404  'homebridge-broadlink-mp' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
why?

**Comment by nitaybz** [comment]
try `sudo npm install -g https://github.com/smka/homebridge-broadlink-mp`

**Comment by smka** [comment]
@eviewei published to npm so you can 
`sudo npm install -g homebridge-broadlink-platform`

**Comment by nitaybz** [comment]
@smka push to npm again?

**Comment by eviewei** [comment]
@smka Thanks! It seems that all broadlink things are going into this platform.
npm install successed, but the plugin name must be "broadlinkMP" and "broadlinkPlatform" can't be recognized. Please update!

**Comment by nitaybz** [comment]
The npm version is not updated yet... therefore it's best if you install from github

**Comment by smka** [comment]
@eviewei published to npm with 0.1.0 version
