### ISSUE TITLE
S1C - Broadlink SmartOne Alarm Kit Support

### ISSUE THREAD

**Issue by nitaybz** [smka/homebridge-broadlink-platform#6]
is there a possibility to add support for the s1c device?
http://www.ibroadlink.com/s1c/

It should support reading the state from the hub (arm, part-arm, disarm)
It has motion sensors and door/window contact sensors
It also has triggered state when the system is armed and one of the sensors is detecting change.

I found a thread about it here:
https://github.com/mjg59/python-broadlink/issues/18
maybe it can help to push it forward...

Thanks :)

**Comment by smka** [comment]
Guys from python-broadlink try to identify and decode packets from this device. 
I can't do a thing without the device. If this one will get support in python library, I'll try to make js implementation.

**Comment by nitaybz** [comment]
They did it!
here:
https://github.com/jazzina/python-broadlink
please help me transform it into javascript...

**Comment by nitaybz** [comment]
Ok I couldn't wait... so I did it myself, inspired and forked from your plugin & library...
[homebridge-broadlink-s1c](https://github.com/nitaybz/homebridge-broadlink-s1c)
